name: Create New Maven Spring Boot Project
author: kadanarpaOps
description: Create a Project using the Github API, Spring CLI and Sonar

inputs:
  project-name:
    required: true
    description: 'Project Name'
  group-id:
    required: true
    description: 'Maven Group ID'
  artifact-id:
    required: true
    description: 'Maven Artifact ID'
  dependencies:
    required: true
    description: 'Maven Dependencies'
  java-version:
    required: false
    description: 'Java Version'
    default: '17'
  jira-key:
    required: true
    description: 'Jira Prefix'
  jira-url:
    required: true
    description: 'Jira Base URL'
  jira-email:
    required: true
    description: 'Jira Account Email'
  jira-token:
    required: true
    description: 'Jira API Token'
  sonar-url:
    required: true
    description: 'Sonar Host URL'
  sonar-token:
    required: true
    description: 'Sonar Host URL'
  template-repo:
    required: true
    description: 'Template Repository URL/Path e.g., kadanarpaOps/Spring-Base-Template'
  github-token:
    required: true
    description: 'Github PAT with the necessaries permissions to create a repository in your account'

runs:
  using: "composite"
  steps:
    - name: Validate & Normalize Project Name
      id: normalize
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        RAW_PROJECT_NAME="${{ inputs.project-name }}"
        RAW_ARTIFACT_ID="${{ inputs.artifact-id }}"
        SLUGIFIED_PROJECT_NAME=$(echo "$RAW_PROJECT_NAME" | sed -E 's/[[:space:]]+/-/g' | sed -E 's/^-+|-+$//g')
        
        echo "Normalized Project Name: '$SLUGIFIED_PROJECT_NAME'"
        
        VALID_NAME_REGEX="^[a-zA-Z0-9]+([a-zA-Z0-9._-]*)$"
        
        if [[ ! "$SLUGIFIED_PROJECT_NAME" =~ $VALID_NAME_REGEX ]]; then
          echo "ERROR: Project Name '$RAW_PROJECT_NAME' (slug: '$SLUGIFIED_PROJECT_NAME') isn't valid."
          echo "The repository name can only contain ASCII letters, digits, and the characters ., -, and _."
          exit 1
        fi
        
        SLUGIFIED_ARTIFACT_ID=$(echo "$RAW_ARTIFACT_ID" | sed -E 's/[[:space:]]+/-/g' | sed -E 's/^-+|-+$//g')
        
        VALID_ARTIFACT_REGEX="^[a-zA-Z0-9]+([a-zA-Z0-9_-]*)$"
        
        echo "Normalized Artifact ID: '$SLUGIFIED_ARTIFACT_ID'"
        
        if [[ ! "$SLUGIFIED_ARTIFACT_ID" =~ $VALID_ARTIFACT_REGEX ]]; then
          echo "ERROR: Artifact ID '$RAW_ARTIFACT_ID' (slug: '$SLUGIFIED_ARTIFACT_ID') isn't valid."
          echo "The repository name can only contain ASCII letters, digits, and the characters - and _."
          exit 1
        fi
        
        TARGET_REPO="${{ github.repository_owner }}/$SLUGIFIED_PROJECT_NAME"
        echo "Verifying if Repository '$TARGET_REPO' already exists>>>"
        
        if gh repo view "$TARGET_REPO" >/dev/null 2>&1; then
          echo "ERROR: Repository '$TARGET_REPO' already exists in your GitHub Account>>>"
          exit 1
        fi
        
        echo "SUCCESS: Repository does not exist and has a valid name."
        
        echo "normalized-project-name=$SLUGIFIED_PROJECT_NAME" >> $GITHUB_OUTPUT

    - name: Checkout Template Engine
      uses: actions/checkout@v4
      with:
        repository: '${{ inputs.template-repo }}'
        token: '${{ inputs.github-token }}'
        path: './workspace-project'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: 'temurin'

    - name: Generate Spring Boot Project
      shell: bash
      run: |
        echo "Generating Spring Boot Project >>>"
        mkdir -p ./tmp-project
        
        curl https://start.spring.io/starter.tgz \
          -d dependencies="${{ inputs.dependencies }}" \
          -d groupId="${{ inputs.group-id }}" \
          -d artifactId="${{ inputs.artifact-id }}" \
          -d name="${{ steps.normalize.outputs.normalized-project-name }}" \
          -d javaVersion="${{ inputs.java-version }}" \
          -d type="maven-project" | tar -xzvf - -C ./tmp-project
        
        rm -f ./tmp-project/.gitignore
        
        echo "Moving Generated Code into Template workspace >>>"
        cp -rn ./tmp-project/* ./workspace-project/ || true
        rm -rf ./tmp-project

    - name: Install POM XML Parser
      shell: bash
      run: |
        npm install \
          --prefix "${{ github.action_path }}" \
          --no-save \
          fast-xml-parser

    - name: Inject Custom Maven Configurations (Sonar & Lombok)
      shell: bash
      run: |
        node "${{ github.action_path }}/scripts/patch-pom.mjs" \
          "./workspace-project/pom.xml"
        
        echo "========================================"
        echo "Generated pom.xml"
        echo "========================================"
        
        cat "./workspace-project/pom.xml"

    - name: Create Project on SonarQube
      shell: bash
      run: |
        echo "Creating Project on SonarQube..."
        PROJECT_KEY="${{ inputs.artifact-id }}"
        PROJECT_NAME="${{ steps.normalize.outputs.normalized-project-name }}"
        
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
          -u "${{ inputs.sonar-token }}:" \
          -X POST "${{ inputs.sonar-url }}/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_NAME}")
        
        echo "Sonar API Response: $RESPONSE"
        if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 400 ]; then
          echo "Failed to create project in SonarQube"
          exit 1
        fi

    - name: Create GitHub Repository & Push Project
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        cd ./workspace-project
        
        echo "Initializing fresh git repository..."
        rm -rf .git
        git init
        git config user.name "kadanarpaOps-Bot"
        git config user.email "bot@kadanarpa.com"
        
        git add .
        git commit -m "setup: initial project structure"
        git branch -M development
        
        REPOSITORY_NAME="${{ steps.normalize.outputs.normalized-project-name }}"
        echo "Creating Repository: $REPOSITORY_NAME"
        
        gh repo create "$REPOSITORY_NAME" --public --source=. --remote=origin
        gh auth setup-git
        git push -u origin development
        
        REMOTE_REPOSITORY="${{ github.repository_owner }}/$REPOSITORY_NAME"
        
        echo "Injecting Jira Secrets to New Repository>>>"
        gh secret set JIRA_KEY -b"${{ inputs.jira-key }}" --repo "$REMOTE_REPOSITORY"
        gh secret set JIRA_URL -b"${{ inputs.jira-url }}" --repo "$REMOTE_REPOSITORY"
        gh secret set JIRA_EMAIL -b"${{ inputs.jira-email }}" --repo "$REMOTE_REPOSITORY"
        gh secret set JIRA_TOKEN -b"${{ inputs.jira-token }}" --repo "$REMOTE_REPOSITORY"
        
        echo "Injecting Sonar Secrets to New Repository>>>"
        gh secret set PROJECT_NAME -b"${{ steps.normalize.outputs.normalized-project-name }}" --repo "$REMOTE_REPOSITORY"
        gh secret set SONAR_URL -b"${{ inputs.sonar-url }}" --repo "$REMOTE_REPOSITORY"
        gh secret set SONAR_TOKEN -b"${{ inputs.sonar-token }}" --repo "$REMOTE_REPOSITORY"
        
        echo "Successfully creation for repository: $REMOTE_REPOSITORY"
