name: Get Jira Issue Info
author: kadanarpa
description: Fetch Issue Status and Type from Jira API

inputs:
  issue-value:
    description: 'Issue ID'
    required: true
  jira-url:
    description: 'Jira Base URL to Fetch'
    required: true
  jira-email:
    description: 'Jira Owner Workspace Email'
    required: true
  jira-token:
    description: 'Jira Permissions Token'
    required: true
  jira-prefix:
    description: 'Jira Code Prefix'
    required: true

outputs:
  status:
    description: "Issue Status"
    value: ${{ steps.fetch-jira.outputs.status }}
  type:
    description: "Issue Type"
    value: ${{ steps.fetch-jira.outputs.type }}

runs:
  using: "composite"
  steps:
    - name: Call Jira API
      id: fetch-jira
      shell: bash
      env:
        ISSUE: ${{ inputs.issue-value }}
        JIRA_URL: ${{ inputs.jira-url }}
        JIRA_EMAIL: ${{ inputs.jira-email }}
        JIRA_TOKEN: ${{ inputs.jira-token }}
        JIRA_PREFIX: ${{ inputs.jira-prefix }}
      run: |
        echo "Validating Issue: ${ISSUE}"
        
        # Extract the Jira key from this commit message
        CLEAN_ISSUE=$(echo "$ISSUE" | tr -d '[](){}')
        echo "CLEAN_ISSUE: ${CLEAN_ISSUE}"
        echo "JIRA_PREFIX raw value: ${JIRA_PREFIX}"
        ISSUE_KEY=$(echo "$CLEAN_ISSUE" | grep -oP "${JIRA_PREFIX}-[0-9]+" | head -1 || true)
        echo "Extracted ISSUE_KEY: '${ISSUE_KEY}'"
        
        if [ -z "$ISSUE_KEY" ]; then
          echo "ERROR: No Jira key found in: '$ISSUE'"
          echo "Expected format: ${JIRA_PREFIX}-NUMBER anywhere in the message."
          exit 1
        fi

        echo "Found key: $ISSUE_KEY. Calling Jira API..."

        # Call the Jira REST API for this specific issue key
        RESPONSE=$(curl -s -w "%{http_code}" \
          -u "$JIRA_EMAIL:$JIRA_TOKEN" \
          -H "Accept: application/json" \
          "$JIRA_URL/rest/api/3/issue/$ISSUE_KEY" \
          -o response.json
        )

        if [ "$RESPONSE" -ne 200 ]; then
          echo "ERROR: Could not fetch issue $ISSUE_KEY from Jira. Code Returned: $RESPONSE"
            if [ "$RESPONSE" -eq 400 ]; then
              echo "Issue does not exists on Jira"
            fi
          exit 1
        fi

        ISSUE_TYPE=$(cat response.json | jq -r '.fields.issuetype.name')
        ISSUE_STATUS=$(cat response.json | jq -r '.fields.status.name')

        echo "Type: $ISSUE_TYPE | Status: $ISSUE_STATUS"
        echo "Exporting to Github Output ENV"
        
        echo "status=$(echo $ISSUE_STATUS)" >> $GITHUB_OUTPUT
        echo "type=$(echo $ISSUE_TYPE)" >> $GITHUB_OUTPUT
