name: Validate Jira Issue
author: kadanarpa
description: >
  Validates that a commit message contains a Jira issue key,
  that the issue exists in the workspace, and that it is of type Story.
  
# NECESSARY INPUTS FOR THE ACTION
inputs:
  jira-workspace-url:
    description: The base URL of the Jira Workspace to be fetch.
    required: true
  jira-project-key:
    description: The Jira Issue Key to validate the Commit.
    required: true
  jira-email:
    description: The email used to authenticate in Jira
    required: true
  jira-api-token:
    description: Jira API Token for authentication
    required: true
  commit-message:
    description: Commit message to be validated
    required: true

runs:
  using: composite
  steps:

    # STEP 1: Extract JIRA Key from the commit message
    - name: 1. Extract Jira Issue Key
      shell: bash
      run: |
        COMMIT_MSG="${{ inputs.commit-message }}"
        JIRA_KEY="${{ inputs.jira-project-key }}"
        
        ISSUE_KEY=$(echo "$COMMIT_MSG" | grep -oP "${JIRA_KEY}-[0-9]+" | head -1)
        
        if [-z "${ISSUE_KEY}" ]; then
          echo "ERROR: Commit message does not contain a valid Jira issue key."
          echo "Expected format: ${JIRA_KEY}-NUMBER anywhere in the message."
          echo "Example: '[${JIRA_KEY}-17] feat: add product listing endpoint'"
          exit 1
        fi
        
        echo "Exporting Issue Key to GitHub Env..."
        echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV
        echo "Found Jira issue key: $ISSUE_KEY"

    # STEP 2: Call Jira REST API to verify Issue Key exists and and is of type Story
    - name: 2. Validate Jira Issue Key through Rest Call
      shell: bash
      run: |
        JIRA_URL="${{ inputs.jira-workspace-url }}"
        JIRA_AUTH_EMAIL="${{ inputs.jira-email}}"
        JIRA_AUTH_TOKEN="${{ inputs.jira-api-token }}"
        
        echo "Rescuing Issue Key from GitHub Env..."
        ISSUE_KEY="${{ env.ISSUE_KEY }}"
        echo "ISSUE RESCUED: ${ISSUE_KEY}"
        
        echo "Preparing Call for Jira REST API to get Issue Details..."
        RESPONSE=$(curl -sf \
          -u "$JIRA_AUTH_EMAIL:$JIRA_AUTH_TOKEN" \
          -H "Accept: application/json" \
          "$JIRA_URL/rest/api/3/issue/$ISSUE_KEY" \
        )
        
        # IF CURL FAILS, EXIT
        if [ $? -ne 0 ]; then
          echo "ERROR: Issue $ISSUE_KEY not found in Jira or authentication failed."
          exit 1
        fi

        # PARSE ISSUE TYPE & StATUS FROM JSON USING JQ
        ISSUE_TYPE=$(echo "$RESPONSE" | jq -r '.fields.issuetype.name')
        ISSUE_STATUS=$(echo "$RESPONSE" | jq -r '.fields.status.name')

        echo "Issue $ISSUE_KEY is of type: $ISSUE_TYPE"
        
        # VALIDATE IF IT IS EXACTLY A STORY
        if [ "$ISSUE_TYPE" != "Story" ]; then
          echo "ERROR: Issue $ISSUE_KEY is of type '$ISSUE_TYPE', but only 'Story' is allowed."
          exit 1
        fi
        
        # VALIDATE IF IT HAS A VALID STATUS
        if [ "$ISSUE_STATUS" != "IN PROGRESS" && "$ISSUE_STATUS" != "NEW" ]; then
          echo "ERROR: Issue $ISSUE_KEY has an invalid STATUS '$ISSUE_STATUS', 'NEW' & 'IN PROGRESS is allowed."
          exit 1
        fi

        echo "ACTION Validation passed: $ISSUE_KEY is a valid Story."