name: CI - App
on:
  workflow_call:
    secrets:
      JIRA_KEY:
        required: true
      JIRA_URL:
        required: true
      JIRA_EMAIL:
        required: true
      JIRA_TOKEN:
        required: true

jobs:
  continuous-integration:
    name: Validate Commits
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT REQUIRED TO ACCESS REPOSITORY CONTENTS
      - name: Checkout Application Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # EXTRACT LASTEST COMMITS SINCE LAST SUCCESSFULLY PUSH
      # - Obtains last successful run  of this same workflow on this same branch
      #   using GitHub API, so if there's no one previous run, we fall back to validate
      #   the HEAD Commits
      - name: Get SHA ID of Last Success Run
        id: last-success
        uses: kadanarpaOps/Ops-Github-Workflows/.github/actions/get-last-success@feature/KAD-2
        with:
          workflow-name: 'commit-validation.yml'

      # EXTRACT COMMIT COUNT TO BE VALIDATED
      # - Obtains last success ShaID from the previous step and use it to extract
      #   the commit list
      - name: Get List of Commit Messages to be Validated
        id: commits-list
        uses: HTTPS-TODOCODE/workflows-reusables/.github/actions/get-commit-list@feature/kadanarpa-actions
        with:
          last-success-sha: ${{ steps.last-success.outputs.shaId }}

      # FINALLY, PROCESS AND VALIDATE EACH COMMIT MESSAGE
      - name: Validate Each Commit against JIRA
        uses: HTTPS-TODOCODE/workflows-reusables/.github/actions/validate-jira-commits@feature/kadanarpa-actions
        with:
          commit-messages: ${{ steps.commits-list.outputs.commit-messages }}
          jira-url: ${{ secrets.JIRA_URL }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-prefix: ${{ secrets.JIRA_KEY }}
