name: Create Feature

on:
  workflow_dispatch:
    inputs:
      feature-name:
        description: >
          Jira Feature Issue Key
          Example Result: feature/KAD-24-add-user-module
        required: true
        type: string

jobs:
  create-feature:
    name: Create Feature branch
    runs-on: ubuntu-latest

    outputs:
      feature_name_valid: ${{ steps.validate-feature-name.outputs.validFeatureName }}

    permissions:
      contents: write

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Validate Feature Name Format
        id: validate-feature-name
        env:
          FEATURE_NAME: ${{ inputs.feature-name }}
        run: |
          node --input-type=module << 'EOF'
          import * as fs from 'fs';
          
          const featureName = process.env.FEATURE_NAME;
          
          if (!/^[A-Za-z0-9-_]+$/.test(featureName)) {
            console.error(`ERROR WARNING: Feature Name "${featureName}" is invalid`);
            console.error('Use only Letters, numbers, underscores and hyphens');
            process.exit(1);
          }
          
          console.log('Valid Feature Name');
          
          const outputName = 'validFeatureName';
          const githubOutput = process.env.GITHUB_OUTPUT;
          
          fs.appendFileSync(githubOutput, `${outputName}=${featureName}\n`);
          console.log(`Set output ${outputName} to ${featureName}\n`)
          
          EOF

      - name: Validate Jira Issue
        id: validate-feature-jira
        uses: ./.github/actions/fetch-jira
        with:
          issue-value: ${{ steps.validate-feature-name.outputs.validFeatureName }}
          jira-url: ${{ secrets.JIRA_URL }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-prefix: ${{ secrets.JIRA_KEY }}

      - name: Validate Jira Feature
        run: |
          ISSUE_STATUS = ${{steps.validate-feature-jira.outputs.status}}
          ISSUE_TYPE = ${{steps.validate-feature-jira.outputs.type}}
          echo "Jira Status: ${ISSUE_STATUS}"
          echo "Jira Type: ${ISSUE_TYPE}"
          
          if [ "$ISSUE_TYPE" != "Story" ]; then
            echo "ERROR: $ISSUE_KEY is type '$ISSUE_TYPE'. Only 'Story' is allowed."
            FAILED=1
            continue
          fi

          if [ "$ISSUE_STATUS" != "NEW" ] && [ "$ISSUE_STATUS" != "IN PROGRESS" ]; then
            echo "ERROR: $ISSUE_KEY has status '$ISSUE_STATUS'."
            echo "Only 'New' and 'In Progress' are allowed."
            FAILED=1
            continue
          fi

      - name: Create and push Feature Branch
        run: |
          node --input-type=module << 'EOF'
          import { execSync } from 'child_process';
          
          const featureName = "${{ steps.validate-feature-name.outputs.validFeatureName }}";
          const branchName = `feature/${featureName}`;
          
          console.log(`Rescued Valid Feature Name: ${featureName}`);
          
          execSync('git config user.name "github-actions[bot]"');
          execSync('git config user.email "github-actions[bot]@users.noreply.github.com"');
          
          try {
            execSync(`git ls-remote --exit-code origin refs/heads/${branchName}`, {
              stdio: 'pipe'
            });
          
            console.error(`ERROR: Branch "${branchName}" already exists.`);
            process.exit(1);
          } catch {
            // Branch does not exist, safe to create
          }

          execSync(`git checkout -b ${branchName}`);
          execSync(`git push origin ${branchName}`);

          console.log(`Branch created and pushed: ${branchName}`);
          
          EOF
