name: Create Branch
on:
  workflow_call:
    inputs:
      branch-name:
        description: >
          Branch Name with Jira Feature Issue Key
          Example Result: feature/KAD-24-add-user-module
        required: true
        type: string
      branch-type:
        description: >
          Branch Type to be Created
          Supported Types: "feature", "bugfix"
        required: true
        type: string
    secrets:
      JIRA_KEY:
        required: true
      JIRA_URL:
        required: true
      JIRA_EMAIL:
        required: true
      JIRA_TOKEN:
        required: true

jobs:
  create-branch:
    name: Validate and Create Branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Execute Branch Creation Action
        uses: kadanarpaOps/Ops-Github-Workflows/.github/actions/create-branch@feature/KAD-2
        with:
          branch-name: ${{ inputs.branch-name }}
          branch-type: ${{ inputs.branch-type }}
          allowed-jira-types: "Feature"
          allowed-jira-statuses: "NEW, IN PROGRESS, Nuevo, En Progreso"
          jira-url: ${{ secrets.JIRA_URL }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-key: ${{ secrets.JIRA_KEY }}
