name: Handle Merged Pull Request
on:
  workflow_call:
    secrets:
      BOT_CLIENT_ID:
        required: true
      BOT_APP_PRIVATE_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  handle-merge:
    name: Propagate, Bump & Publish
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: pr-merged-${{ github.event.pull_request.base.ref }}
      cancel-in-progress: false

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Execute Post-Merge Handling
        uses: kadanarpaOps/Ops-Github-Workflows/.github/actions/pr-merged@main
        with:
          github-token: ${{ steps.github-app-token.outputs.token }}
          destiny-ref: ${{ github.event.pull_request.base.ref }}
          source-ref: ${{ github.event.pull_request.head.ref }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
