name: Sonar Analysis
on:
  workflow_call:
    inputs:
      sonar-quality-gate-wait:
        description: 'Wait for the SonarQube Quality Gate Result before finishing the Workflow'
        required: false
        type: boolean
        default: true
    secrets:
      PROJECT_NAME:
        required: true
      SONAR_URL:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  sonar_analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT REQUIRED TO ACCESS REPOSITORY CONTENTS
      - name: Checkout Application Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # EXECUTE SONARQUBE SCAN
      # !!! JUST MAVEN PROJECTS SUPPORTED BY THE MOMENT
      # - Due the previous checkout now we are on our project content, so the actions
      #   will execute the full project analysis
      - name: Execute SonarQube Analysis
        id: sonar-scan
        uses: HTTPS-TODOCODE/workflows-reusables/.github/actions/sonar-maven-analyze@feature/kadanarpa-actions
        with:
          project-name: ${{ secrets.PROJECT_NAME }}
          sonar-url: ${{ secrets.SONAR_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-quality-gate-wait: ${{ inputs.sonar-quality-gate-wait }}
